### ISSUE TITLE
Update ndarray and sprs deps?

### ISSUE THREAD

**Issue by timmyL17** [espdev/csaps-rs#1]
The ndarray, sprs, and sprs-ldl crates have changed a bit since the last release of csaps. I think the performance bug due to sprs might have been fixed by now? How much work is it to update csaps to the newest versions of those?

I'm having some issues using it currently, due to other dependencies using newer versions of ndarray.

**Comment by espdev** [comment]
Hello,

I can try to update the dependencies and make a new version of csaps crate. 
I didn't know anyone was using csaps in Rust. :)

**Comment by StefanUlbrich** [comment]
Hi,

I started to create a pull request ( #2 ). There is still some work to do on the new slice syntax (will continue maybe next week) but more, severe, the sparse matrix package is not maintained anymore (See PR description)

**Comment by espdev** [comment]
Fixed in #2 and #4 
However, the tests fail now.
